name: Lint CloudFormation Templates

on: 
 push:
    branches: [main, master]

  pull_request:
    branches: [main, master]

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Testing with CFN Lint Command
        uses: scottbrenner/cfn-lint-action@v2
        with:
          command: cfn-lint ./Test/template.yaml
