name: GitGuardian scan

on:
  push:
    branches: [main, master]

  pull_request:
    branches: [main, master]

jobs:
  gitguardian-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: GitGuardian Shield Action
#       uses: gitguardian/gg-shield-action@v1
      uses: GitGuardian/ggshield-action@v1.14.5
      with:
        api_key: ${{ secrets.GG_API_TOKEN }}
        path: '.'
        exclude_regex: '.git'
        types: 'access_key,secret_key'
      
    
      
      
